name: Firebase Deploy

on:
  push:
    branches:
      - master
      - main
      - dev
      - development
      # We're removing the '*' pattern to prevent triggering on automated commits
  pull_request:
    branches:
      - master
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    # Skip if commit message contains any of these skip flags or is from GitHub Actions
    if: >-
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[no ci]') &&
      github.actor != 'github-actions[bot]' &&
      github.actor != 'GitHub-Actions'

    env:
      NODE_VERSION: 22

    # Add permissions for writing to the repository
    permissions:
      contents: write
